image: mechanicalrock/docker-awscli-npm:latest

pipelines:
  default:
      - step:
          name: Deploy to test
          deployment: test
          caches:
            - node
            - yarncustom
          script: 
            - yarn install
            - yarn run deploy:test
            - yarn run deploy:verify
  custom:
    show-env:
    - step:
        script:
        - env | grep -v AWS
    deployment-to-prod:
    - step:
        caches:
          - node
          - yarncustom
        script: 
          - yarn install
          - yarn run deploy:post-verify
          - yarn run deploy:prod
          
definitions:
  caches:
    yarncustom: /usr/local/share/.cache/yarn/v1