image: mechanicalrock/docker-awscli-npm:latest

pipelines:
  default:
      - step:
          name: Deploy to test
          deployment: test
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - yarn install
            - yarn run deploy:test
            - yarn run deploy:verify
      - step:
          name: Verify Deploy
          trigger: manual
          caches:
            - node
          script:
            - yarn run deploy:post-verify
      - step:
          name: Deploy to prod
          caches:
            - pip
            - node
          script: # Modify the commands below to build your repository.
            - yarn install
            - yarn run deploy:prod