image: mechanicalrock/docker-awscli-npm:latest

pipelines:
  default:
      - step:
          name: Deploy to test
          deployment: test
          caches:
            - node
            - yarncustom
          script: # Modify the commands below to build your repository.
            - yarn install
            - yarn run deploy:test
            - yarn run deploy:verify
      - step:
          name: Verify Deploy
          trigger: manual
          caches:
            - node
          script:
            - yarn run deploy:post-verify
      - step:
          name: Deploy to prod
          caches:
            - node
            - yarncustom
          script: # Modify the commands below to build your repository.
            - yarn install
            - yarn run deploy:prod
  custom:
    deployment-to-prod:
      name: Deploy to prod2
      caches:
        - node
        - yarncustom
      script: # Modify the commands below to build your repository.
        - yarn install
        - yarn run deploy:prod
          
definitions:
  caches:
    yarncustom: /usr/local/share/.cache/yarn/v1